import type { Metadata } from "next";
import { Geist, Geist_Mono,Lexend } from "next/font/google";
import { Provider } from "@/components/ui/provider"
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  weight: ['100','200','300','400','500','600', '700','800','900'],
  subsets: ['latin'],
  variable: '--font-lexend'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark overflow-x-hidden md:overflow-x-visible ">
      <body
        className={`${lexend.variable} ${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden md:overflow-x-visible `}
      > 
      
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
